title: "nAIonate"
description: ""


banner:
  image: /assets/images/test.jpeg
  height: "640px"

remote_theme: "jeffreytse/jekyll-theme-yat@v1.10.0"

plugins:
  - jekyll-remote-theme


theme_color: "#FAFAFA"

brand_color: "#183ED6"

lang: "de"
translate_langs:
  - lang: de
    img: https://cdn.countryflags.com/thumbs/germany/flag-400.png
    text: Deutsch
  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English


header_pages:
  - about.md